vim.api.nvim_create_user_command('EditSnip', function()
	require('scissors').editSnippet()
end, {})
vim.api.nvim_create_user_command('AddSnip', function()
	require('scissors').addNewSnippet()
end, {})
