-- :fennel:1704812891
return {
	'tummetott/unimpaired.nvim',
	keys = { ',', '[', ']' },
	opts = {
		default_keymaps = true,
		keymaps = {
			toggle_background = { description = 'Toggle background light/dark', dot_repeat = true, mapping = ',b' },
			toggle_diff = { description = 'Toggle diff', dot_repeat = true, mapping = ',d' },
			toggle_spell = { description = 'Toggle spell check', dot_repeat = true, mapping = ',s' },
			disable_background = false,
			disable_colorcolumn = false,
			disable_cursorcolumn = false,
			disable_cursorcross = false,
			disable_cursorline = false,
			disable_diff = false,
			disable_hlsearch = false,
			disable_ignorecase = false,
			disable_list = false,
			disable_number = false,
			disable_relativenumber = false,
			disable_spell = false,
			disable_virtualedit = false,
			disable_wrap = false,
			enable_background = false,
			enable_colorcolumn = false,
			enable_cursorcolumn = false,
			enable_cursorcross = false,
			enable_cursorline = false,
			enable_diff = false,
			enable_hlsearch = false,
			enable_ignorecase = false,
			enable_list = false,
			enable_number = false,
			enable_relativenumber = false,
			enable_spell = false,
			enable_virtualedit = false,
			enable_wrap = false,
			exchange_above = false,
			exchange_below = false,
			exchange_section_above = false,
			exchange_section_below = false,
			toggle_colorcolumn = false,
			toggle_cursorcolumn = false,
			toggle_cursorcross = false,
			toggle_cursorline = false,
			toggle_ignorecase = false,
			toggle_list = false,
			toggle_number = false,
			toggle_relativenumber = false,
			toggle_virtualedit = false,
			toggle_wrap = false,
		},
	},
}
